CREATE DATABASE cyclus;
USE cyclus;
-- TABELA DO CADASTRO
CREATE TABLE cadastroEmpresa(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome_empresa VARCHAR(70),
    cnpj CHAR(18) NOT NULL UNIQUE,
    email VARCHAR(100) UNIQUE NOT NULL,
		CONSTRAINT chk_emailEmpresa CHECK(email LIKE '%@%'),
    token INT UNIQUE
);

-- TABELA DA USÚARIO
CREATE TABLE usuario(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR (70) NOT NULL,
cpf CHAR(14) UNIQUE NOT NULL,
cargo VARCHAR(20)
		CONSTRAINT chk_cargo CHECK(cargo IN('Master', 'Colaborador')),
email VARCHAR(100) UNIQUE NOT NULL,
		CONSTRAINT chk_email CHECK(email LIKE '%@%'),
senha VARCHAR(12) NOT NULL
);

-- TABELA DO SENSOR COM OS DADOS REGISTRADOS
CREATE TABLE sensor(
	idSensor INT PRIMARY KEY AUTO_INCREMENT,
    modelo VARCHAR(100) NOT NULL,
    tempMax DECIMAL (4,1),
    tempMin DECIMAL(4,1),
    locall VARCHAR(40));

-- TABELA DO REGISTRO DE DADOS
CREATE TABLE registro(
idReg INT PRIMARY KEY AUTO_INCREMENT,
temperaturaAtual DECIMAL (4,1),
horarioRegistro DATETIME DEFAULT CURRENT_TIMESTAMP);
